name: trets-dev

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - gammapy=1.0
  - python=3.9
  - ipython=8.4
  - cython
  - jupyter
  - jupyterlab=3.4.8
  - pyyaml=6.0
  - click=8.1.3
  - numpy=1.23
  - scipy=1.9.1
  - pandas=1.5.0
  - matplotlib=3.6.2
  - astropy=5.1
  - regions=0.6
  - iminuit=2.17
  - naima=0.10.0
  - pydantic=1.9.0
  - emcee=3.1.3
  - corner=2.2.1
  - requests
  - tqdm
  # Added
  - flake8
  - pytest
  - pip:
      - ray[default]>=2.9



    
