name: trets-dev

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  # for gammapy-2.0
  - python=3.12
  - gammapy=2.0
  - ipython=8.27
  - cython
  - jupyter
  - jupyterlab=4.2
  - pyyaml=6.0
  - click=8.2
  - numpy=2.1
  - scipy=1.16
  - pandas=2.2
  - matplotlib=3.9
  - astropy=7.1
  - regions=0.10
  - iminuit=2.31
  - healpy=1.18
  - naima=0.10
  - pydantic=2.11
  - corner=2.2
  - pip
  - requests
  - tqdm
  # Added
  - flake8
  - pytest
  - pip:
     - ray[default]~=2.48.0



    
